//! `SeaORM` Entity, @generated by sea-orm-codegen 2.0

pub mod prelude;

pub mod fish_caught;
pub mod fish_caught_area;
pub mod fish_caught_bait;
pub mod friend_requests;
pub mod herb_quest;
pub mod herb_quest_fish;
pub mod herb_quest_player_state;
pub mod friends;
pub mod inventory_item;
pub mod mail;
pub mod mailbox;
pub mod player_effects;
pub mod stats;
pub mod users;
